[build]
  publish = "dist"
  command = "npm ci --legacy-peer-deps --ignore-engines --no-optional && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps --ignore-engines"
  CI = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  YARN_ENABLED = "false"
  NPM_CONFIG_PACKAGE_MANAGER = "npm"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_CONFIG_IGNORE_ENGINES = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_PROGRESS = "false"
  NPM_CONFIG_LOGLEVEL = "error"
  HUSKY = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
